services:
  flask_app:
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=iam
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=test
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
