"""Init

Revision ID: 4d2a91a862d6
Revises: 
Create Date: 2024-05-27 23:08:49.378662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d2a91a862d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'reviews', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
